[package]
name = "enum_indexing_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.91"
quote = "1.0.17"

[lib]
proc-macro = true